services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    environment:
      USER_INFO_CONNECT_TIMEOUT_MS: 2000
      USER_INFO_READ_TIMEOUT_MS: 10000
      USER_INFO_RETRY_MAX_ATTEMPTS: 1
      USER_INFO_CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE: 1000
      USER_INFO_CIRCUIT_BREAKER_MINIMUM_CALLS: 500
      USER_INFO_CIRCUIT_BREAKER_FAILURE_RATE_THRESHOLD: 90
      USER_INFO_CIRCUIT_BREAKER_TIMEOUT: 10s
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 80
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 20
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT_MS: 10000
      SERVER_TOMCAT_THREADS_MAX: 240
      SERVER_TOMCAT_THREADS_MIN_SPARE: 25
      SERVER_TOMCAT_ACCEPT_COUNT: 500
